### ISSUE TITLE
Builds fail with nuxt generate because there is no ssrContext.req

### ISSUE THREAD

**Issue by gerbenvandijk** [conejerock/nuxt-unleash#1]
Firstly, thanks for this module, it works great for my needs. 

Nuxt has three different modes of operating, client side, server side, and static (generated).

Client side and server side work fine, but when running `yarn run generate` (static), there are build errors because in this context, there is no  `ssrContext.req` object.

I have fixed this for my situation by changing `plugin.ts:17` to:

`  if (process.server && ssrContext && ssrContext.req && ssrContext.req.socket) {`

For now my problem is solved because I applied this fix to a clone of your codebase that I published to a private npm repository, but it would be great to implement this fix so I can keep on using your module for this.

This issue is probably specific to me, as part of our app is static (for important SEO pages) and part of it is client side only (the part behind login). The static pages should never need any feature checks anyways, so the above solution fixes the problem completely for my current needs. 

However, I can imagine there are other scenario's where it would be useful to re-hydrate the IP address in the store and revalidate enabled features on the client side. That way it would still be possible to use the IP related strategies on static sites.

If needed, I can also create a PR for this fix and see if I can contribute to deal with the above scenario further if you'd like!

**Comment by conejerock** [comment]
Thank you very much for feedback.
Added, solved and tested in https://github.com/conejerock/nuxt-unleash/commit/8ed4c7be87670d598e959c2e983498dff09e8d4f. 💪💪
