### ISSUE TITLE
strategies don't seem to work

### ISSUE THREAD

**Issue by arnfox** [conejerock/nuxt-unleash#5]
Hello! Thanks for the package. Looks really good. Feature flags are working (only with full nuxt rebuild though, cannot change during the runtime) Although I don't seem to be able to use Strategies. It shows strategy properly during the nuxt build. But it doesn't seem to take it into account when I use
`this.feature = this.$unleash.isEnabled('test');` (always true, even if the strategy only allows certain user id's which I don't provide to the `isEnabled` function context. Any advice?

**Comment by conejerock** [comment]
Hi @arnfox. The documentation may need to be updated.
You need to use `isAllowUser` with the feature flag name and userId. 
```
this.feature = this.$unleash.isAllowUser('test', 'myUsername');
```
Also, if a feature flag does not exist it defaults to `true`. 
You can modify this in the module options with `enabledDefault: false`.
